# Generated by Django 4.0.4 on 2023-11-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0002_remove_bloglist_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogList',
            new_name='Blog',
        ),
    ]
