# Generated by Django 4.0.4 on 2023-11-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0005_add_relationname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='Categoryyy',
        ),
    ]
